[theme]
primaryColor        = "#37633D"   # Hijau tua — WARNA UTAMA/PRIMARY
backgroundColor     = "#FFFFFF"
secondaryBackgroundColor = "#A9C9AD"  # Sage muda
textColor           = "#0F172A"   # Near-black
font                = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
